add component testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,6 +21,28 @@ jobs:
     with:
       environment: "${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) && 'production' || 'preview' }} "
 
+  deploy-status:
+    name: Deploy Status
+    needs: [deploy]
+    if: success() || failure()
+    runs-on: ubuntu-latest
+    env:
+      STATUS: "${{ contains(needs.*.result, 'failure') && 'failed' || 'passed' }}"
+      MESSAGE: "Latest deployment available at ${{ needs.deploy.outputs.url }}"
+    steps:
+      - name: Add preview URL to job summary
+        run: |
+          echo "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
+      - name: Add preview URL to PR
+        if: github.event_name == 'pull_request'
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          message: |
+            "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
+      - name: Failing deploy
+        if: ${{ env.STATUS == 'failed' }}
+        run: exit 1
+
   lint:
     name: Lint
     runs-on: ubuntu-latest
@@ -49,28 +71,6 @@ jobs:
     with:
       url: ""
       tag: "@component"
-
-  deploy-status:
-    name: Deploy Status
-    needs: [deploy]
-    if: success() || failure()
-    runs-on: ubuntu-latest
-    env:
-      STATUS: "${{ contains(needs.*.result, 'failure') && 'failed' || 'passed' }}"
-      MESSAGE: "Latest deployment available at ${{ needs.deploy.outputs.url }}"
-    steps:
-      - name: Add preview URL to job summary
-        run: |
-          echo "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
-      - name: Add preview URL to PR
-        if: github.event_name == 'pull_request'
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          message: |
-            "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
-      - name: Failing deploy
-        if: ${{ env.STATUS == 'failed' }}
-        run: exit 1
 
   smoke-test:
     name: Smoke Test
